services:
  automatic1111-forge:
    container_name: automatic1111-forge
    image: automatic1111-forge:0.1
    restart: always
    build:
      context: .
    ports:
      - "7861:7860"
    volumes:
      - ./models:/home/aiuser/stable-diffusion-webui-forge/models
      - automatic1111-forge:/home/aiuser/stable-diffusion-webui-forge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
volumes:
  automatic1111-forge:
    driver: local