services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "5000:11434"
    volumes:
      - "./storage/ollama:/root/.ollama"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: ['gpu']

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "5001:8080"
    volumes:
      - "./storage/webui:/app/backend/data"

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "5002:9099"
    volumes:
      - "./storage/pipelines:/app/pipelines"

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5003:5678"
    volumes:
      - "./storage/n8n_data:/home/node/.n8n"

